### ISSUE TITLE
Problem with ASCII in `README.md` file

### ISSUE THREAD

**Issue by gabrielbdornas** [infovote-io/dashboard#1]
In [this commit](https://github.com/infovote-io/dashboard/commit/8706b3eab987744cee9caa7f4461ef687a3fc00e) my ASCII didn't work inside `README.md` file:

![image](https://github.com/infovote-io/dashboard/assets/49699290/8cae25a7-2f16-42ef-833f-f3f7fca8d440)

As we could see in the picture above, the error `Missing open brace for subscript` is shown in the screen.

**Comment by gabrielbdornas** [comment]
@danybonfil please fix this error, as we discussed this morning.

**Comment by danybonfil** [comment]
The error is caused by the characters "{ }" in the ASCII art that are interpreted as special characters in Markdown. To fix this issue, I modified the ASCII art to use a monospaced code block and prefix each line of ASCII art with four spaces. This will display the ASCII art as a code block but keep it visible in the rendered output.

<img width="686" alt="image" src="https://github.com/infovote-io/dashboard/assets/43021461/e654b56c-e236-4556-8925-56e38fb37e2f">
