### ISSUE TITLE
Add all R graphs

### ISSUE THREAD

**Issue by gabrielbdornas** [infovote-io/dashboard#16]

**Comment by danybonfil** [comment]
As shown in #5 the RDI plots for $US and %Growth are working. We managed to plot the cumulative %Growth after manually removing the NAs from the csv. This will be fixed directly in the csv:



![Image](https://github.com/infovote-io/dashboard/assets/43021461/415edfcf-7b86-408b-906e-066d85cde701)

**Comment by danybonfil** [comment]
I included the two graphs of the paper to start the conversation with a simple test. How do we perceive the performance of two different economies. 

<img width="722" alt="image" src="https://github.com/infovote-io/dashboard/assets/43021461/57bcdf64-d697-42c3-8303-72dd28a54636">
Each presidential term lasts 4 years but as it can be seen above, the last year is being cutoff 1980 and 1996. 

![image](https://github.com/infovote-io/dashboard/assets/43021461/38ba6050-8f1d-4a7e-b37d-e3a043ade3c5)
This was also happening with the complete dataset for the first year and the last. (For example, if the dataset starts in 1960 the graph would start in 1959. Similarly, if it end in 2022 it would be cutoff at 2021.  
I removed the columns of presidents and values for 1960, 2021, 2022, and 2023 but this error persisted)

I included the format "utcyymm" as this [tutorial](https://github.com/vega/vega-lite/issues/4044) shows. This small change allowed me to filter data for smaller timeframes, and for the graph to start with the desired date. However, it was not enough to prevent the last year of being cutoff. 
In the graphs with all data, the error was still "off-by-one" in all of them. Instead of slicing the date, I wil try encoding it directly in Vega Lite.
