### ISSUE TITLE
Save ETL dataframe in a `csv` file

### ISSUE THREAD

**Issue by gabrielbdornas** [infovote-io/dashboard#5]
@danybonfil as we discussed, I need that the dataframe used to generate the graphs saved in a `csv` file.

**Comment by danybonfil** [comment]
Data from the FRED API retrieves Real Disposable Income (RDI) in $US levels
I use simple log transform to calculate yearly growth: value = log(value / lag(value)) * 100)

A separate json list with presidents name is used for filtering data. 
For example, Joe Biden (2024) means his term would include years 2021, 2022, 2023, and 2024 when elections take place

Dataframe is saved as "df_data" in the main repository folder

<img width="548" alt="image" src="https://github.com/infovote-io/dashboard/assets/43021461/9a858294-99f9-40a5-9378-dd778f30ab0f">

**Comment by danybonfil** [comment]
Using Vega Lite, I was able to plot the usvalue and growth graphs but could not include the [cumulative graph](https://vega.github.io/vega-lite/examples/area_cumulative_freq.html). This was caused because the csv had NA in the year 1960 which is the base year to calculate growth and for the year 2023 that has no values yet.

To solve this, I reopen this issue to include a line of code that removes NAs. I will also modify the contents of the csv that currently are: date (years), usvalue (RDI in dollars), and value (RDI %growth) to also include the cumulative growth (cumsum of RDI %growth) and the names of the presidents.


![Image](https://github.com/infovote-io/dashboard/assets/43021461/63dcff92-2a6e-4dac-b753-60cee68f1e19)

**Comment by gabrielbdornas** [comment]
@danybonfil I'll close this issue. From now on, remember to use `See #issue_number` and `Fix #issue_number` to link issues and commits!
